-- ============================================================================
-- MIGRATION: Create Vision Gallery
-- ============================================================================

-- 1. Create avatar_visions table
CREATE TABLE IF NOT EXISTS public.avatar_visions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    wish_id uuid REFERENCES public.user_wishes(id) ON DELETE SET NULL,
    prompt text NOT NULL, -- Original user/short prompt
    refined_prompt text NOT NULL, -- Detailed prompt generated by Gemini
    image_url text NOT NULL, -- Final Pollinations.ai URL or stored URL
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (id)
);

-- Enable RLS
ALTER TABLE public.avatar_visions ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own visions"
    ON public.avatar_visions FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own visions"
    ON public.avatar_visions FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_avatar_visions_user_id ON public.avatar_visions(user_id);
